In [1]:
from numpy import poly1d

In [2]:
p = poly1d([3,6,8])
print(p)

   2
3 x + 6 x + 8


In [3]:
print(p*p)

   4      3      2
9 x + 36 x + 84 x + 96 x + 64


In [4]:
p.r

array([-1.+1.29099445j, -1.-1.29099445j])

In [5]:
p

poly1d([3, 6, 8])

In [6]:
p1 = poly1d([1,2,3], variable = 'q')
print(p1)

   2
1 q + 2 q + 3


In [11]:
print(p.integ(k=6))

   3     2
1 x + 3 x + 8 x + 6


In [12]:
print(p.deriv())

 
6 x + 6


In [16]:
import scipy.special as ss
import numpy as np

In [14]:
a = np.arange(1,12)

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
ss.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469,
       2.22398009])

In [18]:
x=4
ss.exp2(x)

16.0

In [19]:
ss.exp10(5)

100000.0

In [21]:
d= 30
m = 20 
s =60
ss.radian(d,m,s)

0.529707427980279

In [24]:
ss.sindg(30)


0.49999999999999994

In [25]:
ss.tandg(45)

1.0

In [26]:
ss.comb(5,3)

10.0

In [27]:
ss.perm(5,3)

60.0

In [29]:
import scipy.integrate as scin

In [31]:
def f(x):
    return x**2
f(4)

16

In [32]:
f = lambda x,y : x+y
f(3,6)

9

In [33]:
f = lambda x: x+2
t = scin.quad(f, 1, 2)
t

(3.5, 3.885780586188048e-14)

In [34]:
from numpy import exp

In [35]:
f = lambda x: exp(-x**2)
r = scin.quad(f, 1, 3)
r

(0.1393832154470942, 1.5474645503565277e-15)

In [36]:
q = scin.dblquad(lambda x , y : x+y, 1,2, lambda x:0, lambda y:1+2*y)

In [37]:
q

(14.33333333333333, 2.4934234575921986e-13)

In [38]:
from scipy import linalg 


In [40]:
a1 = np.array([[1,2], [3,4]])
a1

array([[1, 2],
       [3, 4]])

In [41]:
linalg.det(a1)

-2.0